<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Traits\DataInsertSeeder;

class ColorSeeder extends Seeder
{
    use DataInsertSeeder;
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $this->insertSeed([
            ['color_code' => '#000000' , 'name' =>  'Black'],
            ['color_code' => '#0C090A' , 'name' =>  'Night'],
            ['color_code' => '#34282C' , 'name' =>  'Charcoal'],
            ['color_code' => '#3B3131' , 'name' =>  'Oil'],
            ['color_code' => '#3A3B3C' , 'name' =>  'Dark Gray'],
            ['color_code' => '#454545' , 'name' =>  'Light Black'],
            ['color_code' => '#413839' , 'name' =>  'Black Cat'],
            ['color_code' => '#3D3C3A' , 'name' =>  'Iridium'],
            ['color_code' => '#463E3F' , 'name' =>  'Black Eel'],
            ['color_code' => '#4C4646' , 'name' =>  'Black Cow'],
            ['color_code' => '#504A4B' , 'name' =>  'Gray Wolf'],
            ['color_code' => '#565051' , 'name' =>  'Vampire Gray'],
            ['color_code' => '#52595D' , 'name' =>  'Iron Gray'],
            ['color_code' => '#5C5858' , 'name' =>  'Gray Dolphin'],
            ['color_code' => '#625D5D' , 'name' =>  'Carbon Gray'],
            ['color_code' => '#666362' , 'name' =>  'Ash Gray'],
            ['color_code' => '#696969' , 'name' =>  'DimGray or DimGrey'],
            ['color_code' => '#686A6C' , 'name' =>  'Nardo Gray'],
            ['color_code' => '#6D6968' , 'name' =>  'Cloudy Gray'],
            ['color_code' => '#726E6D' , 'name' =>  'Smokey Gray'],
            ['color_code' => '#736F6E' , 'name' =>  'Alien Gray'],
            ['color_code' => '#757575' , 'name' =>  'Sonic Silver'],
            ['color_code' => '#797979' , 'name' =>  'Platinum Gray'],
            ['color_code' => '#837E7C' , 'name' =>  'Granite'],
            ['color_code' => '#808080' , 'name' =>  'Gray or Grey'],
            ['color_code' => '#848482' , 'name' =>  'Battleship Gray'],
            ['color_code' => '#8D918D' , 'name' =>  'Gunmetal Gray'],
            ['color_code' => '#A9A9A9' , 'name' =>  'DarkGray or DarkGrey'],
            ['color_code' => '#B6B6B4' , 'name' =>  'Gray Cloud'],
            ['color_code' => '#C0C0C0' , 'name' =>  'Silver'],
            ['color_code' => '#C9C0BB' , 'name' =>  'Pale Silver'],
            ['color_code' => '#D1D0CE' , 'name' =>  'Gray Goose'],
            ['color_code' => '#CECECE' , 'name' =>  'Platinum Silver'],
            ['color_code' => '#D3D3D3' , 'name' =>  'LightGray or LightGrey'],
            ['color_code' => '#DCDCDC' , 'name' =>  'Gainsboro'],
            ['color_code' => '#E5E4E2' , 'name' =>  'Platinum'],
            ['color_code' => '#BCC6CC' , 'name' =>  'Metallic Silver'],
            ['color_code' => '#98AFC7' , 'name' =>  'Blue Gray'],
            ['color_code' => '#838996' , 'name' =>  'Roman Silver'],
            ['color_code' => '#778899' , 'name' =>  'LightSlateGray or LightSlateGrey'],
            ['color_code' => '#708090' , 'name' =>  'SlateGray or SlateGrey'],
            ['color_code' => '#6D7B8D' , 'name' =>  'Rat Gray'],
            ['color_code' => '#657383' , 'name' =>  'Slate Granite Gray'],
            ['color_code' => '#616D7E' , 'name' =>  'Jet Gray'],
            ['color_code' => '#646D7E' , 'name' =>  'Mist Blue'],
            ['color_code' => '#566D7E' , 'name' =>  'Marble Blue'],
            ['color_code' => '#737CA1' , 'name' =>  'Slate Blue Grey'],
            ['color_code' => '#728FCE' , 'name' =>  'Light Purple Blue'],
            ['color_code' => '#4863A0' , 'name' =>  'Azure Blue'],
            ['color_code' => '#2B547E' , 'name' =>  'Blue Jay'],
            ['color_code' => '#36454F' , 'name' =>  'Charcoal Blue'],
            ['color_code' => '#29465B' , 'name' =>  'Dark Blue Grey'],
            ['color_code' => '#2B3856' , 'name' =>  'Dark Slate'],
            ['color_code' => '#123456' , 'name' =>  'Deep-Sea Blue'],
            ['color_code' => '#151B54' , 'name' =>  'Night Blue'],
            ['color_code' => '#191970' , 'name' =>  'MidnightBlue'],
            ['color_code' => '#000080' , 'name' =>  'Navy'],
            ['color_code' => '#151B8D' , 'name' =>  'Denim Dark Blue'],
            ['color_code' => '#00008B' , 'name' =>  'DarkBlue'],
            ['color_code' => '#15317E' , 'name' =>  'Lapis Blue'],
            ['color_code' => '#0000A0' , 'name' =>  'New Midnight Blue'],
            ['color_code' => '#0000A5' , 'name' =>  'Earth Blue'],
            ['color_code' => '#0020C2' , 'name' =>  'Cobalt Blue'],
            ['color_code' => '#0000CD' , 'name' =>  'MediumBlue'],
            ['color_code' => '#0041C2' , 'name' =>  'Blueberry Blue'],
            ['color_code' => '#2916F5' , 'name' =>  'Canary Blue'],
            ['color_code' => '#0000FF' , 'name' =>  'Blue'],
            ['color_code' => '#0909FF' , 'name' =>  'Bright Blue'],
            ['color_code' => '#1F45FC' , 'name' =>  'Blue Orchid'],
            ['color_code' => '#2554C7' , 'name' =>  'Sapphire Blue'],
            ['color_code' => '#1569C7' , 'name' =>  'Blue Eyes'],
            ['color_code' => '#1974D2' , 'name' =>  'Bright Navy Blue'],
            ['color_code' => '#2B60DE' , 'name' =>  'Balloon Blue'],
            ['color_code' => '#4169E1' , 'name' =>  'RoyalBlue'],
            ['color_code' => '#2B65EC' , 'name' =>  'Ocean Blue'],
            ['color_code' => '#306EFF' , 'name' =>  'Blue Ribbon'],
            ['color_code' => '#157DEC' , 'name' =>  'Blue Dress'],
            ['color_code' => '#1589FF' , 'name' =>  'Neon Blue'],
            ['color_code' => '#1E90FF' , 'name' =>  'DodgerBlue'],
            ['color_code' => '#368BC1' , 'name' =>  'Glacial Blue Ice'],
            ['color_code' => '#4682B4' , 'name' =>  'SteelBlue'],
            ['color_code' => '#488AC7' , 'name' =>  'Silk Blue'],
            ['color_code' => '#357EC7' , 'name' =>  'Windows Blue'],
            ['color_code' => '#3090C7' , 'name' =>  'Blue Ivy'],
            ['color_code' => '#659EC7' , 'name' =>  'Blue Koi'],
            ['color_code' => '#87AFC7' , 'name' =>  'Columbia Blue'],
            ['color_code' => '#95B9C7' , 'name' =>  'Baby Blue'],
            ['color_code' => '#6495ED' , 'name' =>  'CornflowerBlue'],
            ['color_code' => '#6698FF' , 'name' =>  'Sky Blue Dress'],
            ['color_code' => '#56A5EC' , 'name' =>  'Iceberg'],
            ['color_code' => '#38ACEC' , 'name' =>  'Butterfly Blue'],
            ['color_code' => '#00BFFF' , 'name' =>  'DeepSkyBlue'],
            ['color_code' => '#3BB9FF' , 'name' =>  'Midday Blue'],
            ['color_code' => '#5CB3FF' , 'name' =>  'Crystal Blue'],
            ['color_code' => '#79BAEC' , 'name' =>  'Denim Blue'],
            ['color_code' => '#82CAFF' , 'name' =>  'Day Sky Blue'],
            ['color_code' => '#87CEFA' , 'name' =>  'LightSkyBlue'],
            ['color_code' => '#87CEEB' , 'name' =>  'SkyBlue'],
            ['color_code' => '#A0CFEC' , 'name' =>  'Jeans Blue'],
            ['color_code' => '#B7CEEC' , 'name' =>  'Blue Angel'],
            ['color_code' => '#B4CFEC' , 'name' =>  'Pastel Blue'],
            ['color_code' => '#ADDFFF' , 'name' =>  'Light Day Blue'],
            ['color_code' => '#C2DFFF' , 'name' =>  'Sea Blue'],
            ['color_code' => '#C6DEFF' , 'name' =>  'Heavenly Blue'],
            ['color_code' => '#BDEDFF' , 'name' =>  'Robin Egg Blue'],
            ['color_code' => '#B0E0E6' , 'name' =>  'PowderBlue'],
            ['color_code' => '#AFDCEC' , 'name' =>  'Coral Blue'],
            ['color_code' => '#ADD8E6' , 'name' =>  'LightBlue'],
            ['color_code' => '#B0CFDE' , 'name' =>  'LightSteelBlue'],
            ['color_code' => '#C9DFEC' , 'name' =>  'Gulf Blue'],
            ['color_code' => '#D5D6EA' , 'name' =>  'Pastel Light Blue'],
            ['color_code' => '#E3E4FA' , 'name' =>  'Lavender Blue'],
            ['color_code' => '#E6E6FA' , 'name' =>  'Lavender'],
            ['color_code' => '#EBF4FA' , 'name' =>  'Water'],
            ['color_code' => '#F0F8FF' , 'name' =>  'AliceBlue'],
            ['color_code' => '#F8F8FF' , 'name' =>  'GhostWhite'],
            ['color_code' => '#F0FFFF' , 'name' =>  'Azure'],
            ['color_code' => '#E0FFFF' , 'name' =>  'LightCyan'],
            ['color_code' => '#CCFFFF' , 'name' =>  'Light Slate'],
            ['color_code' => '#9AFEFF' , 'name' =>  'Electric Blue'],
            ['color_code' => '#7DFDFE' , 'name' =>  'Tron Blue'],
            ['color_code' => '#57FEFF' , 'name' =>  'Blue Zircon'],
            ['color_code' => '#00FFFF' , 'name' =>  'Aqua or Cyan'],
            ['color_code' => '#0AFFFF' , 'name' =>  'Bright Cyan'],
            ['color_code' => '#50EBEC' , 'name' =>  'Celeste'],
            ['color_code' => '#4EE2EC' , 'name' =>  'Blue Diamond'],
            ['color_code' => '#16E2F5' , 'name' =>  'Bright Turquoise'],
            ['color_code' => '#8EEBEC' , 'name' =>  'Blue Lagoon'],
            ['color_code' => '#AFEEEE' , 'name' =>  'PaleTurquoise'],
            ['color_code' => '#CFECEC' , 'name' =>  'Pale Blue Lily'],
            ['color_code' => '#81D8D0' , 'name' =>  'Tiffany Blue'],
            ['color_code' => '#77BFC7' , 'name' =>  'Blue Hosta'],
            ['color_code' => '#92C7C7' , 'name' =>  'Cyan Opaque'],
            ['color_code' => '#78C7C7' , 'name' =>  'Northern Lights Blue'],
            ['color_code' => '#7BCCB5' , 'name' =>  'Blue Green'],
            ['color_code' => '#66CDAA' , 'name' =>  'MediumAquaMarine'],
            ['color_code' => '#AAF0D1' , 'name' =>  'Magic Mint'],
            ['color_code' => '#7FFFD4' , 'name' =>  'Aquamarine'],
            ['color_code' => '#93FFE8' , 'name' =>  'Light Aquamarine'],
            ['color_code' => '#40E0D0' , 'name' =>  'Turquoise'],
            ['color_code' => '#48D1CC' , 'name' =>  'MediumTurquoise'],
            ['color_code' => '#48CCCD' , 'name' =>  'Deep Turquoise'],
            ['color_code' => '#46C7C7' , 'name' =>  'Jellyfish'],
            ['color_code' => '#43C6DB' , 'name' =>  'Blue Turquoise'],
            ['color_code' => '#00CED1' , 'name' =>  'DarkTurquoise'],
            ['color_code' => '#43BFC7' , 'name' =>  'Macaw Blue Green'],
            ['color_code' => '#20B2AA' , 'name' =>  'LightSeaGreen'],
            ['color_code' => '#3EA99F' , 'name' =>  'Seafoam Green'],
            ['color_code' => '#5F9EA0' , 'name' =>  'CadetBlue'],
            ['color_code' => '#3B9C9C' , 'name' =>  'Deep-Sea'],
            ['color_code' => '#008B8B' , 'name' =>  'DarkCyan'],
            ['color_code' => '#008080' , 'name' =>  'Teal'],
            ['color_code' => '#045F5F' , 'name' =>  'Medium Teal'],
            ['color_code' => '#033E3E' , 'name' =>  'Deep Teal'],
            ['color_code' => '#25383C' , 'name' =>  'DarkSlateGray or DarkSlateGrey'],
            ['color_code' => '#2C3539' , 'name' =>  'Gunmetal'],
            ['color_code' => '#3C565B' , 'name' =>  'Blue Moss Green'],
            ['color_code' => '#4C787E' , 'name' =>  'Beetle Green'],
            ['color_code' => '#5E7D7E' , 'name' =>  'Grayish Turquoise'],
            ['color_code' => '#307D7E' , 'name' =>  'Greenish Blue'],
            ['color_code' => '#348781' , 'name' =>  'Aquamarine Stone'],
            ['color_code' => '#438D80' , 'name' =>  'Sea Turtle Green'],
            ['color_code' => '#4E8975' , 'name' =>  'Dull-Sea Green'],
            ['color_code' => '#306754' , 'name' =>  'Deep-Sea Green'],
            ['color_code' => '#2E8B57' , 'name' =>  'SeaGreen'],
            ['color_code' => '#31906E' , 'name' =>  'Dark Mint'],
            ['color_code' => '#00A36C' , 'name' =>  'Jade'],
            ['color_code' => '#34A56F' , 'name' =>  'Earth Green'],
            ['color_code' => '#50C878' , 'name' =>  'Emerald'],
            ['color_code' => '#3EB489' , 'name' =>  'Mint'],
            ['color_code' => '#3CB371' , 'name' =>  'MediumSeaGreen'],
            ['color_code' => '#78866B' , 'name' =>  'Camouflage Green'],
            ['color_code' => '#848B79' , 'name' =>  'Sage Green'],
            ['color_code' => '#617C58' , 'name' =>  'Hazel Green'],
            ['color_code' => '#728C00' , 'name' =>  'Venom Green'],
            ['color_code' => '#6B8E23' , 'name' =>  'OliveDrab'],
            ['color_code' => '#808000' , 'name' =>  'Olive'],
            ['color_code' => '#556B2F' , 'name' =>  'DarkOliveGreen'],
            ['color_code' => '#4B5320' , 'name' =>  'Army Green'],
            ['color_code' => '#667C26' , 'name' =>  'Fern Green'],
            ['color_code' => '#4E9258' , 'name' =>  'Fall Forest Green'],
            ['color_code' => '#387C44' , 'name' =>  'Pine Green'],
            ['color_code' => '#347235' , 'name' =>  'Medium Forest Green'],
            ['color_code' => '#347C2C' , 'name' =>  'Jungle Green'],
            ['color_code' => '#228B22' , 'name' =>  'ForestGreen'],
            ['color_code' => '#008000' , 'name' =>  'Green'],
            ['color_code' => '#006400' , 'name' =>  'DarkGreen'],
            ['color_code' => '#046307' , 'name' =>  'Deep Emerald Green'],
            ['color_code' => '#254117' , 'name' =>  'Dark Forest Green'],
            ['color_code' => '#437C17' , 'name' =>  'Seaweed Green'],
            ['color_code' => '#347C17' , 'name' =>  'Shamrock Green'],
            ['color_code' => '#6AA121' , 'name' =>  'Green Onion'],
            ['color_code' => '#4AA02C' , 'name' =>  'Green Pepper'],
            ['color_code' => '#41A317' , 'name' =>  'Dark Lime Green'],
            ['color_code' => '#12AD2B' , 'name' =>  'Parrot Green'],
            ['color_code' => '#3EA055' , 'name' =>  'Clover Green'],
            ['color_code' => '#73A16C' , 'name' =>  'Dinosaur Green'],
            ['color_code' => '#6CBB3C' , 'name' =>  'Green Snake'],
            ['color_code' => '#6CC417' , 'name' =>  'Alien Green'],
            ['color_code' => '#4CC417' , 'name' =>  'Green Apple'],
            ['color_code' => '#32CD32' , 'name' =>  'LimeGreen'],
            ['color_code' => '#52D017' , 'name' =>  'Pea Green'],
            ['color_code' => '#4CC552' , 'name' =>  'Kelly Green'],
            ['color_code' => '#54C571' , 'name' =>  'Zombie Green'],
            ['color_code' => '#99C68E' , 'name' =>  'Frog Green'],
            ['color_code' => '#8FBC8F' , 'name' =>  'DarkSeaGreen'],
            ['color_code' => '#89C35C' , 'name' =>  'Green Peas'],
            ['color_code' => '#85BB65' , 'name' =>  'Dollar Bill Green'],
            ['color_code' => '#9CB071' , 'name' =>  'Iguana Green'],
            ['color_code' => '#B0BF1A' , 'name' =>  'Acid Green'],
            ['color_code' => '#B2C248' , 'name' =>  'Avocado Green'],
            ['color_code' => '#9DC209' , 'name' =>  'Pistachio Green'],
            ['color_code' => '#A1C935' , 'name' =>  'Salad Green'],
            ['color_code' => '#9ACD32' , 'name' =>  'YellowGreen'],
            ['color_code' => '#77DD77' , 'name' =>  'Pastel Green'],
            ['color_code' => '#7FE817' , 'name' =>  'Hummingbird Green'],
            ['color_code' => '#59E817' , 'name' =>  'Nebula Green'],
            ['color_code' => '#57E964' , 'name' =>  'Stoplight Go Green'],
            ['color_code' => '#16F529' , 'name' =>  'Neon Green'],
            ['color_code' => '#5EFB6E' , 'name' =>  'Jade Green'],
            ['color_code' => '#36F57F' , 'name' =>  'Lime Mint Green'],
            ['color_code' => '#00FF7F' , 'name' =>  'SpringGreen'],
            ['color_code' => '#00FA9A' , 'name' =>  'MediumSpringGreen'],
            ['color_code' => '#5FFB17' , 'name' =>  'Emerald Green'],
            ['color_code' => '#00FF00' , 'name' =>  'Lime'],
            ['color_code' => '#7CFC00' , 'name' =>  'LawnGreen'],
            ['color_code' => '#66FF00' , 'name' =>  'Bright Green'],
            ['color_code' => '#7FFF00' , 'name' =>  'Chartreuse'],
            ['color_code' => '#87F717' , 'name' =>  'Yellow Lawn Green'],
            ['color_code' => '#98F516' , 'name' =>  'Aloe Vera Green'],
            ['color_code' => '#B1FB17' , 'name' =>  'Dull Green Yellow'],
            ['color_code' => '#ADFF2F' , 'name' =>  'GreenYellow'],
            ['color_code' => '#BDF516' , 'name' =>  'Chameleon Green'],
            ['color_code' => '#DAEE01' , 'name' =>  'Neon Yellow Green'],
            ['color_code' => '#E2F516' , 'name' =>  'Yellow Green Grosbeak'],
            ['color_code' => '#CCFB5D' , 'name' =>  'Tea Green'],
            ['color_code' => '#BCE954' , 'name' =>  'Slime Green'],
            ['color_code' => '#64E986' , 'name' =>  'Algae Green'],
            ['color_code' => '#90EE90' , 'name' =>  'LightGreen'],
            ['color_code' => '#6AFB92' , 'name' =>  'Dragon Green'],
            ['color_code' => '#98FB98' , 'name' =>  'PaleGreen'],
            ['color_code' => '#98FF98' , 'name' =>  'Mint Green'],
            ['color_code' => '#B5EAAA' , 'name' =>  'Green Thumb'],
            ['color_code' => '#E3F9A6' , 'name' =>  'Organic Brown'],
            ['color_code' => '#C3FDB8' , 'name' =>  'Light Jade'],
            ['color_code' => '#DBF9DB' , 'name' =>  'Light Rose Green'],
            ['color_code' => '#F0FFF0' , 'name' =>  'HoneyDew'],
            ['color_code' => '#F5FFFA' , 'name' =>  'MintCream'],
            ['color_code' => '#FFFACD' , 'name' =>  'LemonChiffon'],
            ['color_code' => '#FFFFC2' , 'name' =>  'Parchment'],
            ['color_code' => '#FFFFCC' , 'name' =>  'Cream'],
            ['color_code' => '#FFFDD0' , 'name' =>  'Cream White'],
            ['color_code' => '#FAFAD2' , 'name' =>  'LightGoldenRodYellow'],
            ['color_code' => '#FFFFE0' , 'name' =>  'LightYellow'],
            ['color_code' => '#F5F5DC' , 'name' =>  'Beige'],
            ['color_code' => '#FFF8DC' , 'name' =>  'Cornsilk'],
            ['color_code' => '#FBF6D9' , 'name' =>  'Blonde'],
            ['color_code' => '#F7E7CE' , 'name' =>  'Champagne'],
            ['color_code' => '#FAEBD7' , 'name' =>  'AntiqueWhite'],
            ['color_code' => '#FFEFD5' , 'name' =>  'PapayaWhip'],
            ['color_code' => '#FFEBCD' , 'name' =>  'BlanchedAlmond'],
            ['color_code' => '#FFE4C4' , 'name' =>  'Bisque'],
            ['color_code' => '#F5DEB3' , 'name' =>  'Wheat'],
            ['color_code' => '#FFE4B5' , 'name' =>  'Moccasin'],
            ['color_code' => '#FFE5B4' , 'name' =>  'Peach'],
            ['color_code' => '#FED8B1' , 'name' =>  'Light Orange'],
            ['color_code' => '#FFDAB9' , 'name' =>  'PeachPuff'],
            ['color_code' => '#FFDEAD' , 'name' =>  'NavajoWhite'],
            ['color_code' => '#FBE7A1' , 'name' =>  'Golden Blonde'],
            ['color_code' => '#F3E3C3' , 'name' =>  'Golden Silk'],
            ['color_code' => '#F0E2B6' , 'name' =>  'Dark Blonde'],
            ['color_code' => '#F1E5AC' , 'name' =>  'Light Gold'],
            ['color_code' => '#F3E5AB' , 'name' =>  'Vanilla'],
            ['color_code' => '#ECE5B6' , 'name' =>  'Tan Brown'],
            ['color_code' => '#E8E4C9' , 'name' =>  'Dirty White'],
            ['color_code' => '#EEE8AA' , 'name' =>  'PaleGoldenRod'],
            ['color_code' => '#F0E68C' , 'name' =>  'Khaki'],
            ['color_code' => '#EDDA74' , 'name' =>  'Cardboard Brown'],
            ['color_code' => '#EDE275' , 'name' =>  'Harvest Gold'],
            ['color_code' => '#FFE87C' , 'name' =>  'Sun Yellow'],
            ['color_code' => '#FFF380' , 'name' =>  'Corn Yellow'],
            ['color_code' => '#FAF884' , 'name' =>  'Pastel Yellow'],
            ['color_code' => '#FFFF33' , 'name' =>  'Neon Yellow'],
            ['color_code' => '#FFFF00' , 'name' =>  'Yellow'],
            ['color_code' => '#FFEF00' , 'name' =>  'Canary Yellow'],
            ['color_code' => '#F5E216' , 'name' =>  'Banana Yellow'],
            ['color_code' => '#FFDB58' , 'name' =>  'Mustard Yellow'],
            ['color_code' => '#FFDF00' , 'name' =>  'Golden Yellow'],
            ['color_code' => '#F9DB24' , 'name' =>  'Bold Yellow'],
            ['color_code' => '#FFD801' , 'name' =>  'Rubber Ducky Yellow'],
            ['color_code' => '#FFD700' , 'name' =>  'Gold'],
            ['color_code' => '#FDD017' , 'name' =>  'Bright Gold'],
            ['color_code' => '#FFCE44' , 'name' =>  'Chrome Gold'],
            ['color_code' => '#EAC117' , 'name' =>  'Golden Brown'],
            ['color_code' => '#F6BE00' , 'name' =>  'Deep Yellow'],
            ['color_code' => '#F2BB66' , 'name' =>  'Macaroni and Cheese'],
            ['color_code' => '#FBB917' , 'name' =>  'Saffron'],
            ['color_code' => '#FBB117' , 'name' =>  'Beer'],
            ['color_code' => '#FFAE42' , 'name' =>  'Yellow Orange or Orange Yellow'],
            ['color_code' => '#FFA62F' , 'name' =>  'Cantaloupe'],
            ['color_code' => '#FFA500' , 'name' =>  'Orange'],
            ['color_code' => '#EE9A4D' , 'name' =>  'Brown Sand'],
            ['color_code' => '#F4A460' , 'name' =>  'SandyBrown'],
            ['color_code' => '#E2A76F' , 'name' =>  'Brown Sugar'],
            ['color_code' => '#C19A6B' , 'name' =>  'Camel Brown'],
            ['color_code' => '#E6BF83' , 'name' =>  'Deer Brown'],
            ['color_code' => '#DEB887' , 'name' =>  'BurlyWood'],
            ['color_code' => '#D2B48C' , 'name' =>  'Tan'],
            ['color_code' => '#C8AD7F' , 'name' =>  'Light French Beige'],
            ['color_code' => '#C2B280' , 'name' =>  'Sand'],
            ['color_code' => '#BCB88A' , 'name' =>  'Sage'],
            ['color_code' => '#C8B560' , 'name' =>  'Fall Leaf Brown'],
            ['color_code' => '#C9BE62' , 'name' =>  'Ginger Brown'],
            ['color_code' => '#BDB76B' , 'name' =>  'DarkKhaki'],
            ['color_code' => '#BAB86C' , 'name' =>  'Olive Green'],
            ['color_code' => '#B5A642' , 'name' =>  'Brass'],
            ['color_code' => '#C7A317' , 'name' =>  'Cookie Brown'],
            ['color_code' => '#D4AF37' , 'name' =>  'Metallic Gold'],
            ['color_code' => '#E9AB17' , 'name' =>  'Bee Yellow'],
            ['color_code' => '#E8A317' , 'name' =>  'School Bus Yellow'],
            ['color_code' => '#DAA520' , 'name' =>  'GoldenRod'],
            ['color_code' => '#D4A017' , 'name' =>  'Orange Gold'],
            ['color_code' => '#C68E17' , 'name' =>  'Caramel'],
            ['color_code' => '#B8860B' , 'name' =>  'DarkGoldenRod'],
            ['color_code' => '#C58917' , 'name' =>  'Cinnamon'],
            ['color_code' => '#CD853F' , 'name' =>  'Peru'],
            ['color_code' => '#CD7F32' , 'name' =>  'Bronze'],
            ['color_code' => '#C88141' , 'name' =>  'Tiger Orange'],
            ['color_code' => '#B87333' , 'name' =>  'Copper'],
            ['color_code' => '#AA6C39' , 'name' =>  'Dark Gold'],
            ['color_code' => '#AB784E' , 'name' =>  'Dark Almond'],
            ['color_code' => '#966F33' , 'name' =>  'Wood'],
            ['color_code' => '#806517' , 'name' =>  'Oak Brown'],
            ['color_code' => '#665D1E' , 'name' =>  'Antique Bronze'],
            ['color_code' => '#8E7618' , 'name' =>  'Hazel'],
            ['color_code' => '#8B8000' , 'name' =>  'Dark Yellow'],
            ['color_code' => '#827839' , 'name' =>  'Dark Moccasin'],
            ['color_code' => '#8A865D' , 'name' =>  'Khaki Green'],
            ['color_code' => '#AF9B60' , 'name' =>  'Bullet Shell'],
            ['color_code' => '#827B60' , 'name' =>  'Army Brown'],
            ['color_code' => '#786D5F' , 'name' =>  'Sandstone'],
            ['color_code' => '#483C32' , 'name' =>  'Taupe'],
            ['color_code' => '#493D26' , 'name' =>  'Mocha'],
            ['color_code' => '#513B1C' , 'name' =>  'Milk Chocolate'],
            ['color_code' => '#3D3635' , 'name' =>  'Gray Brown'],
            ['color_code' => '#3B2F2F' , 'name' =>  'Dark Coffee'],
            ['color_code' => '#43302E' , 'name' =>  'Old Burgundy'],
            ['color_code' => '#49413F' , 'name' =>  'Western Charcoal'],
            ['color_code' => '#5C3317' , 'name' =>  'Bakers Brown'],
            ['color_code' => '#654321' , 'name' =>  'Dark Brown'],
            ['color_code' => '#704214' , 'name' =>  'Sepia Brown'],
            ['color_code' => '#804A00' , 'name' =>  'Dark Bronze'],
            ['color_code' => '#6F4E37' , 'name' =>  'Coffee'],
            ['color_code' => '#835C3B' , 'name' =>  'Brown Bear'],
            ['color_code' => '#7F5217' , 'name' =>  'Red Dirt'],
            ['color_code' => '#7F462C' , 'name' =>  'Sepia'],
            ['color_code' => '#A0522D' , 'name' =>  'Sienna'],
            ['color_code' => '#8B4513' , 'name' =>  'SaddleBrown'],
            ['color_code' => '#8A4117' , 'name' =>  'Dark Sienna'],
            ['color_code' => '#7E3817' , 'name' =>  'Sangria'],
            ['color_code' => '#7E3517' , 'name' =>  'Blood Red'],
            ['color_code' => '#954535' , 'name' =>  'Chestnut'],
            ['color_code' => '#C34A2C' , 'name' =>  'Chestnut Red'],
            ['color_code' => '#C04000' , 'name' =>  'Mahogany'],
            ['color_code' => '#C35817' , 'name' =>  'Red Fox'],
            ['color_code' => '#B86500' , 'name' =>  'Dark Bisque'],
            ['color_code' => '#B5651D' , 'name' =>  'Light Brown'],
            ['color_code' => '#B76734' , 'name' =>  'Petra Gold'],
            ['color_code' => '#C36241' , 'name' =>  'Rust'],
            ['color_code' => '#CB6D51' , 'name' =>  'Copper Red'],
            ['color_code' => '#C47451' , 'name' =>  'Orange Salmon'],
            ['color_code' => '#D2691E' , 'name' =>  'Chocolate'],
            ['color_code' => '#CC6600' , 'name' =>  'Sedona'],
            ['color_code' => '#E56717' , 'name' =>  'Papaya Orange'],
            ['color_code' => '#E66C2C' , 'name' =>  'Halloween Orange'],
            ['color_code' => '#FF6700' , 'name' =>  'Neon Orange'],
            ['color_code' => '#FF5F1F' , 'name' =>  'Bright Orange'],
            ['color_code' => '#F87217' , 'name' =>  'Pumpkin Orange'],
            ['color_code' => '#F88017' , 'name' =>  'Carrot Orange'],
            ['color_code' => '#FF8C00' , 'name' =>  'DarkOrange'],
            ['color_code' => '#F87431' , 'name' =>  'Construction Cone Orange'],
            ['color_code' => '#FF7722' , 'name' =>  'Indian Saffron'],
            ['color_code' => '#E67451' , 'name' =>  'Sunrise Orange'],
            ['color_code' => '#FF8040' , 'name' =>  'Mango Orange'],
            ['color_code' => '#FF7F50' , 'name' =>  'Coral'],
            ['color_code' => '#F88158' , 'name' =>  'Basket Ball Orange'],
            ['color_code' => '#F9966B' , 'name' =>  'Light Salmon Rose'],
            ['color_code' => '#FFA07A' , 'name' =>  'LightSalmon'],
            ['color_code' => '#E9967A' , 'name' =>  'DarkSalmon'],
            ['color_code' => '#E78A61' , 'name' =>  'Tangerine'],
            ['color_code' => '#DA8A67' , 'name' =>  'Light Copper'],
            ['color_code' => '#FA8072' , 'name' =>  'Salmon'],
            ['color_code' => '#F08080' , 'name' =>  'LightCoral'],
            ['color_code' => '#F67280' , 'name' =>  'Pastel Red'],
            ['color_code' => '#E77471' , 'name' =>  'Pink Coral'],
            ['color_code' => '#F75D59' , 'name' =>  'Bean Red'],
            ['color_code' => '#E55451' , 'name' =>  'Valentine Red'],
            ['color_code' => '#CD5C5C' , 'name' =>  'IndianRed'],
            ['color_code' => '#FF6347' , 'name' =>  'Tomato'],
            ['color_code' => '#E55B3C' , 'name' =>  'Shocking Orange'],
            ['color_code' => '#FF4500' , 'name' =>  'OrangeRed'],
            ['color_code' => '#FF0000' , 'name' =>  'Red'],
            ['color_code' => '#FD1C03' , 'name' =>  'Neon Red'],
            ['color_code' => '#FF2400' , 'name' =>  'Scarlet'],
            ['color_code' => '#F62217' , 'name' =>  'Ruby Red'],
            ['color_code' => '#F70D1A' , 'name' =>  'Ferrari Red'],
            ['color_code' => '#F62817' , 'name' =>  'Fire Engine Red'],
            ['color_code' => '#E42217' , 'name' =>  'Lava Red'],
            ['color_code' => '#E41B17' , 'name' =>  'Love Red'],
            ['color_code' => '#DC381F' , 'name' =>  'Grapefruit'],
            ['color_code' => '#C24641' , 'name' =>  'Cherry Red'],
            ['color_code' => '#C11B17' , 'name' =>  'Chilli Pepper'],
            ['color_code' => '#B22222' , 'name' =>  'FireBrick'],
            ['color_code' => '#B21807' , 'name' =>  'Tomato Sauce Red'],
            ['color_code' => '#A52A2A' , 'name' =>  'Brown'],
            ['color_code' => '#A70D2A' , 'name' =>  'Carbon Red'],
            ['color_code' => '#9F000F' , 'name' =>  'Cranberry'],
            ['color_code' => '#931314' , 'name' =>  'Saffron Red'],
            ['color_code' => '#990000' , 'name' =>  'Crimson Red'],
            ['color_code' => '#990012' , 'name' =>  'Red Wine or Wine Red'],
            ['color_code' => '#8B0000' , 'name' =>  'DarkRed'],
            ['color_code' => '#800000' , 'name' =>  'Maroon'],
            ['color_code' => '#8C001A' , 'name' =>  'Burgundy'],
            ['color_code' => '#7E191B' , 'name' =>  'Vermilion'],
            ['color_code' => '#800517' , 'name' =>  'Deep Red'],
            ['color_code' => '#660000' , 'name' =>  'Red Blood'],
            ['color_code' => '#551606' , 'name' =>  'Blood Night'],
            ['color_code' => '#560319' , 'name' =>  'Dark Scarlet'],
            ['color_code' => '#3D0C02' , 'name' =>  'Black Bean'],
            ['color_code' => '#3F000F' , 'name' =>  'Chocolate Brown'],
            ['color_code' => '#2B1B17' , 'name' =>  'Midnight'],
            ['color_code' => '#550A35' , 'name' =>  'Purple Lily'],
            ['color_code' => '#810541' , 'name' =>  'Purple Maroon'],
            ['color_code' => '#7D0541' , 'name' =>  'Plum Pie'],
            ['color_code' => '#7D0552' , 'name' =>  'Plum Velvet'],
            ['color_code' => '#872657' , 'name' =>  'Dark Raspberry'],
            ['color_code' => '#7E354D' , 'name' =>  'Velvet Maroon'],
            ['color_code' => '#7F4E52' , 'name' =>  'Rosy-Finch'],
            ['color_code' => '#7F525D' , 'name' =>  'Dull Purple'],
            ['color_code' => '#7F5A58' , 'name' =>  'Puce'],
            ['color_code' => '#997070' , 'name' =>  'Rose Dust'],
            ['color_code' => '#B38481' , 'name' =>  'Rosy Pink'],
            ['color_code' => '#BC8F8F' , 'name' =>  'RosyBrown'],
            ['color_code' => '#C5908E' , 'name' =>  'Khaki Rose'],
            ['color_code' => '#C48793' , 'name' =>  'Lipstick Pink'],
            ['color_code' => '#C48189' , 'name' =>  'Pink Brown'],
            ['color_code' => '#E799A3' , 'name' =>  'Pink Daisy'],
            ['color_code' => '#D58A94' , 'name' =>  'Dusty Pink'],
            ['color_code' => '#E8ADAA' , 'name' =>  'Rose'],
            ['color_code' => '#C4AEAD' , 'name' =>  'Silver Pink'],
            ['color_code' => '#ECC5C0' , 'name' =>  'Rose Gold'],
            ['color_code' => '#FFCBA4' , 'name' =>  'Deep Peach'],
            ['color_code' => '#F8B88B' , 'name' =>  'Pastel Orange'],
            ['color_code' => '#EDC9AF' , 'name' =>  'Desert Sand'],
            ['color_code' => '#FFDDCA' , 'name' =>  'Unbleached Silk'],
            ['color_code' => '#FDD7E4' , 'name' =>  'Pig Pink'],
            ['color_code' => '#FFE6E8' , 'name' =>  'Blush'],
            ['color_code' => '#FFE4E1' , 'name' =>  'MistyRose'],
            ['color_code' => '#FFDFDD' , 'name' =>  'Pink Bubble Gum'],
            ['color_code' => '#FFCCCB' , 'name' =>  'Light Red'],
            ['color_code' => '#FBCFCD' , 'name' =>  'Light Rose'],
            ['color_code' => '#FBBBB9' , 'name' =>  'Deep Rose'],
            ['color_code' => '#FFC0CB' , 'name' =>  'Pink'],
            ['color_code' => '#FFB6C1' , 'name' =>  'LightPink'],
            ['color_code' => '#FAAFBE' , 'name' =>  'Donut Pink'],
            ['color_code' => '#FAAFBA' , 'name' =>  'Baby Pink'],
            ['color_code' => '#F9A7B0' , 'name' =>  'Flamingo Pink'],
            ['color_code' => '#FEA3AA' , 'name' =>  'Pastel Pink'],
            ['color_code' => '#E7A1B0' , 'name' =>  'Rose Pink or Pink Rose'],
            ['color_code' => '#E38AAE' , 'name' =>  'Cadillac Pink'],
            ['color_code' => '#F778A1' , 'name' =>  'Carnation Pink'],
            ['color_code' => '#E56E94' , 'name' =>  'Blush Red'],
            ['color_code' => '#DB7093' , 'name' =>  'PaleVioletRed'],
            ['color_code' => '#D16587' , 'name' =>  'Purple Pink'],
            ['color_code' => '#C25A7C' , 'name' =>  'Tulip Pink'],
            ['color_code' => '#C25283' , 'name' =>  'Bashful Pink'],
            ['color_code' => '#E75480' , 'name' =>  'Dark Pink'],
            ['color_code' => '#F660AB' , 'name' =>  'Dark Hot Pink'],
            ['color_code' => '#FF69B4' , 'name' =>  'HotPink'],
            ['color_code' => '#FC6C85' , 'name' =>  'Watermelon Pink'],
            ['color_code' => '#F6358A' , 'name' =>  'Violet Red'],
            ['color_code' => '#F52887' , 'name' =>  'Hot Deep Pink'],
            ['color_code' => '#FF1493' , 'name' =>  'DeepPink'],
            ['color_code' => '#F535AA' , 'name' =>  'Neon Pink'],
            ['color_code' => '#FD349C' , 'name' =>  'Neon Hot Pink'],
            ['color_code' => '#E45E9D' , 'name' =>  'Pink Cupcake'],
            ['color_code' => '#E3319D' , 'name' =>  'Dimorphotheca Magenta'],
            ['color_code' => '#E4287C' , 'name' =>  'Pink Lemonade'],
            ['color_code' => '#E30B5D' , 'name' =>  'Raspberry'],
            ['color_code' => '#DC143C' , 'name' =>  'Crimson'],
            ['color_code' => '#C32148' , 'name' =>  'Bright Maroon'],
            ['color_code' => '#C21E56' , 'name' =>  'Rose Red'],
            ['color_code' => '#C12869' , 'name' =>  'Rogue Pink'],
            ['color_code' => '#C12267' , 'name' =>  'Burnt Pink'],
            ['color_code' => '#CA226B' , 'name' =>  'Pink Violet'],
            ['color_code' => '#C71585' , 'name' =>  'MediumVioletRed'],
            ['color_code' => '#C12283' , 'name' =>  'Dark Carnation Pink'],
            ['color_code' => '#B3446C' , 'name' =>  'Raspberry Purple'],
            ['color_code' => '#B93B8F' , 'name' =>  'Pink Plum'],
            ['color_code' => '#DA70D6' , 'name' =>  'Orchid'],
            ['color_code' => '#DF73D4' , 'name' =>  'Deep Mauve'],
            ['color_code' => '#EE82EE' , 'name' =>  'Violet'],
            ['color_code' => '#F433FF' , 'name' =>  'Bright Neon Pink'],
            ['color_code' => '#FF00FF' , 'name' =>  'Fuchsia or Magenta'],
            ['color_code' => '#E238EC' , 'name' =>  'Crimson Purple'],
            ['color_code' => '#D462FF' , 'name' =>  'Heliotrope Purple'],
            ['color_code' => '#C45AEC' , 'name' =>  'Tyrian Purple'],
            ['color_code' => '#BA55D3' , 'name' =>  'MediumOrchid'],
            ['color_code' => '#A74AC7' , 'name' =>  'Purple Flower'],
            ['color_code' => '#B048B5' , 'name' =>  'Orchid Purple'],
            ['color_code' => '#D291BC' , 'name' =>  'Pastel Violet'],
            ['color_code' => '#915F6D' , 'name' =>  'Mauve Taupe'],
            ['color_code' => '#7E587E' , 'name' =>  'Viola Purple'],
            ['color_code' => '#614051' , 'name' =>  'Eggplant'],
            ['color_code' => '#583759' , 'name' =>  'Plum Purple'],
            ['color_code' => '#5E5A80' , 'name' =>  'Grape'],
            ['color_code' => '#4E5180' , 'name' =>  'Purple Navy'],
            ['color_code' => '#6A5ACD' , 'name' =>  'SlateBlue'],
            ['color_code' => '#6960EC' , 'name' =>  'Blue Lotus'],
            ['color_code' => '#736AFF' , 'name' =>  'Light Slate Blue'],
            ['color_code' => '#7B68EE' , 'name' =>  'MediumSlateBlue'],
            ['color_code' => '#7575CF' , 'name' =>  'Periwinkle Purple'],
            ['color_code' => '#6667AB' , 'name' =>  'Very Peri'],
            ['color_code' => '#6F2DA8' , 'name' =>  'Bright Grape'],
            ['color_code' => '#6C2DC7' , 'name' =>  'Purple Amethyst'],
            ['color_code' => '#6A0DAD' , 'name' =>  'Bright Purple'],
            ['color_code' => '#5453A6' , 'name' =>  'Deep Periwinkle'],
            ['color_code' => '#483D8B' , 'name' =>  'DarkSlateBlue'],
            ['color_code' => '#4E387E' , 'name' =>  'Purple Haze'],
            ['color_code' => '#571B7E' , 'name' =>  'Purple Iris'],
            ['color_code' => '#4B0150' , 'name' =>  'Dark Purple'],
            ['color_code' => '#36013F' , 'name' =>  'Deep Purple'],
            ['color_code' => '#461B7E' , 'name' =>  'Purple Monster'],
            ['color_code' => '#4B0082' , 'name' =>  'Indigo'],
            ['color_code' => '#342D7E' , 'name' =>  'Blue Whale'],
            ['color_code' => '#663399' , 'name' =>  'RebeccaPurple'],
            ['color_code' => '#6A287E' , 'name' =>  'Purple Jam'],
            ['color_code' => '#8B008B' , 'name' =>  'DarkMagenta'],
            ['color_code' => '#800080' , 'name' =>  'Purple'],
            ['color_code' => '#86608E' , 'name' =>  'French Lilac'],
            ['color_code' => '#9932CC' , 'name' =>  'DarkOrchid'],
            ['color_code' => '#9400D3' , 'name' =>  'DarkViolet'],
            ['color_code' => '#8D38C9' , 'name' =>  'Purple Violet'],
            ['color_code' => '#A23BEC' , 'name' =>  'Jasmine Purple'],
            ['color_code' => '#B041FF' , 'name' =>  'Purple Daffodil'],
            ['color_code' => '#842DCE' , 'name' =>  'Clematis Violet'],
            ['color_code' => '#8A2BE2' , 'name' =>  'BlueViolet'],
            ['color_code' => '#7A5DC7' , 'name' =>  'Purple Sage Bush'],
            ['color_code' => '#7F38EC' , 'name' =>  'Lovely Purple'],
            ['color_code' => '#9D00FF' , 'name' =>  'Neon Purple'],
            ['color_code' => '#8E35EF' , 'name' =>  'Purple Plum'],
            ['color_code' => '#893BFF' , 'name' =>  'Aztech Purple'],
            ['color_code' => '#967BB6' , 'name' =>  'Lavender Purple'],
            ['color_code' => '#9370DB' , 'name' =>  'MediumPurple'],
            ['color_code' => '#8467D7' , 'name' =>  'Light Purple'],
            ['color_code' => '#9172EC' , 'name' =>  'Crocus Purple'],
            ['color_code' => '#9E7BFF' , 'name' =>  'Purple Mimosa'],
            ['color_code' => '#CCCCFF' , 'name' =>  'Periwinkle'],
            ['color_code' => '#DCD0FF' , 'name' =>  'Pale Lilac'],
            ['color_code' => '#E0B0FF' , 'name' =>  'Mauve'],
            ['color_code' => '#D891EF' , 'name' =>  'Bright Lilac'],
            ['color_code' => '#B666D2' , 'name' =>  'Rich Lilac'],
            ['color_code' => '#C38EC7' , 'name' =>  'Purple Dragon'],
            ['color_code' => '#C8A2C8' , 'name' =>  'Lilac'],
            ['color_code' => '#DDA0DD' , 'name' =>  'Plum'],
            ['color_code' => '#E6A9EC' , 'name' =>  'Blush Pink'],
            ['color_code' => '#F2A2E8' , 'name' =>  'Pastel Purple'],
            ['color_code' => '#F9B7FF' , 'name' =>  'Blossom Pink'],
            ['color_code' => '#C6AEC7' , 'name' =>  'Wisteria Purple'],
            ['color_code' => '#D2B9D3' , 'name' =>  'Purple Thistle'],
            ['color_code' => '#D8BFD8' , 'name' =>  'Thistle'],
            ['color_code' => '#E9CFEC' , 'name' =>  'Periwinkle Pink'],
            ['color_code' => '#FCDFFF' , 'name' =>  'Cotton Candy'],
            ['color_code' => '#EBDDE2' , 'name' =>  'Lavender Pinocchio'],
            ['color_code' => '#E1D9D1' , 'name' =>  'Dark White'],
            ['color_code' => '#E9E4D4' , 'name' =>  'Ash White'],
            ['color_code' => '#EDE6D6' , 'name' =>  'White Chocolate'],
            ['color_code' => '#FAF0DD' , 'name' =>  'Soft Ivory'],
            ['color_code' => '#F8F0E3' , 'name' =>  'Off White'],
            ['color_code' => '#F8F6F0' , 'name' =>  'Pearl White'],
            ['color_code' => '#FFF0F5' , 'name' =>  'LavenderBlush'],
            ['color_code' => '#FDEEF4' , 'name' =>  'Pearl'],
            ['color_code' => '#FFF9E3' , 'name' =>  'Egg Shell'],
            ['color_code' => '#FDF5E6' , 'name' =>  'OldLace'],
            ['color_code' => '#FAF0E6' , 'name' =>  'Linen'],
            ['color_code' => '#FFF5EE' , 'name' =>  'SeaShell'],
            ['color_code' => '#FAF5EF' , 'name' =>  'Rice'],
            ['color_code' => '#FFFAF0' , 'name' =>  'FloralWhite'],
            ['color_code' => '#FFFFF0' , 'name' =>  'Ivory'],
            ['color_code' => '#FFFFF7' , 'name' =>  'Light White'],
            ['color_code' => '#F5F5F5' , 'name' =>  'WhiteSmoke'],
            ['color_code' => '#FBFBF9' , 'name' =>  'Cotton'],
            ['color_code' => '#FFFAFA' , 'name' =>  'Snow'],
            ['color_code' => '#FEFCFF' , 'name' =>  'Milk White'],
            ['color_code' => '#FFFFFF' , 'name' =>  'White']
        ],'Color','colors');
}
}
